# This file defines a CI/CD workflow to run in Github Actions with focus on deployment

# This workflow shall deploy the flutter app to various platforms
# and shall only run when the build workflow is executed or completed
# using the workflow_run event as a trigger
# Source: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run

name: Flutter Deploy to various Platforms

on:
  workflow_run:
    workflows: [ "Flutter Build for various Platforms" ]
    types:
      - completed
    branches: [ main ]

  workflow_dispatch:

jobs:
  on-build-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The build workflow that triggered this workflow passed'
      - run: echo 'We shall now deploy to different platforms'

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The build workflow that triggered this workflow failed'
      - run: echo 'We shall now notify administrators of this failure'
