# This file defines a CI/CD workflow to run in Github Actions to release a preview of the application

# This workflow shall build the flutter app for the web
# and shall only run when a push event is carried out on branches
# other than the specified branch(es)

# Name of workflow.
name: Flutter Build and Deploy Application Preview

on:
  # NB: This event will only trigger when not on branches specified in `branches-ignore`
  push:
    branches-ignore:
      - "main"
      - "master"

  workflow_dispatch:

jobs:
  build_and_preview:
    runs-on: ubuntu-latest

    steps:
      # The branch or tag ref that triggered the workflow will be checked out.
      # See: https://github.com/actions/checkout
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Avail Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Clean up and Get dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Build application for deployment on website
        run: flutter build web --web-renderer canvaskit --dart-define="flavor=${ENVIRONMENT}"

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Deploy to Firebase Hosting (Preview)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAGIC_FITNESS_APP }}'
          expires: 30d  # length of time preview channel should remain active after the last deploy
          projectId: ${{ secrets.FIREBASE_WEB_APPID }}
          channelId: 'pr-${{ github.event.number }}-${{ steps.extract_branch.outputs.branch }}'
